### ISSUE TITLE
Cannot hide, disable and move cursor left or right in Qt5

### ISSUE THREAD

**Issue by jorgesmok** [anntzer/mplcursors#1]
I'm using Python 3.6, PyQt 5.6 and matplotlib 2.0.0.  I cannot get the 'toggle-visibility' and ‘toggle_enabled’ keys to work. Neither Shift-Left and Shift-Right move the cursor “left” or “right” by one data point. Do I need to do something specific for this when using Qt5Agg backend?

**Comment by anntzer** [comment]
Things "should" work out of the box, so let's investigate...

Are you running mplcursors 0.1 or master?  (0.2 is probably overdue as I made quite a few changes)
What happens when you run examples/event_handling/keypress_demo.py from the matplotlib source tree (https://github.com/matplotlib/matplotlib/blob/master/examples/event_handling/keypress_demo.py)?  In particular, do keypress events ("e", "v", "shift+left", "shift+right") get reported?

**Comment by jorgesmok** [comment]
I'm running mplcursors 0.1. Yes, those keypress events get reported when I run that example.

**Comment by anntzer** [comment]
Can you try master?
Looks like "e" and "v" are actually not working as of 0.1 (which means I definitely need to make a new release) but shift-left/right do work for me.

**Comment by jorgesmok** [comment]
Sorry I'm a newbie to GitHub, I am trying to install with `python -mpip install git+https://github.com/anntzer/mplcursors` but I get
error: could not open 'C:\Users\Jorge\AppData\Local\Temp\tmpkvhuq02y': Permission denied. 
I'm using Windows 10 and excecuted command prompt as administrator. I've done some googling to avoid that permission denial but can't find the solution.

**Comment by anntzer** [comment]
You should probably report this issue to the pip github repo.

Meanwhile you can try
```
pip install https://github.com/anntzer/mplcursors/archive/master.zip
```
or just download the zip ("mplcursors-master.zip") manually from github (the green "clone or download" button) and do
```
pip install mplcursors-master.zip
```

**Comment by jorgesmok** [comment]
I couldn't get it installed by any of those ways. But I got the commands shift+left and shift+right working on version 0.1, 'e' and 'v' doesn't work as you said. My problem was because my qt5 canvas didn't have focus set on. This issue was due to my incompetence with qt5, however it looks like I helped you find the 'e' and 'v' issue.

**Comment by anntzer** [comment]
No worries.  I updated the docs (https://mplcursors.readthedocs.io/en/latest/ for the current version) accordingly, feel free to let me know if anything is unclear.
