### ISSUE TITLE
mplcursors crashing Python under certain conditions. While mpldatacursor works.

### ISSUE THREAD

**Issue by skbobade** [anntzer/mplcursors#12]
mplcursors crashing Python under certain conditions. While mpldatacursor works - 
Is there any way for me to provide logs? I am not able to reproduce the issue on a smaller example code that I can share. 

Issue basically manifests as crash of Python when attempting to add annotation.

**Comment by anntzer** [comment]
Please provide *some* way for me to reproduce, or at least observe this, e.g. screenshots, tracebacks, etc.

**Comment by anntzer** [comment]
There's no logging.  Screenshots, perhaps?

**Comment by anntzer** [comment]
I'm going to close this as there is no way for me to know under what conditions you observe a crash.  Feel free to ping for a reopen with more information (source code, screenshots, screen videos, etc.).
