### ISSUE TITLE
Don't use `blit` with matplotlib>=3.0.0

### ISSUE THREAD

**Issue by StSav012** [anntzer/mplcursors#14]
When one sets multiple cursors one over the other and then clicks right mouse button to remove the latest cursor, all of them get removed. To avoid the behavior, I have added `break` to the loop in `_on_key_press` function. To my surprise, now all the cursor balloons disappear but only one gets removed. When I set the cursor invisible and back visible, I see the remaining balloons. It seems that using `blit` is not the best idea due to the `matplotlib` annotation bug. Please change

```ann.draggable(use_blit=True)```

to 

```ann.draggable(use_blit=False)```

or, better, add an option to remove just one balloon and an option to turn `blit` off.

**Comment by anntzer** [comment]
I think this is already fixed on master (basically since https://github.com/anntzer/mplcursors/issues/10); can you confirm?

**Comment by StSav012** [comment]
Oh, indeed. The https://github.com/anntzer/mplcursors/issues/10 issue description is far too poor. Waiting for the pip version to catch up with the repo.
