### ISSUE TITLE
[Feature Request] Vertical Marker style cursors

### ISSUE THREAD

**Issue by dwij2812** [anntzer/mplcursors#15]
Can you try to add vertical markers that can be varied along the X axis to display the corresponding Y values on the plots. This is somewhat like those markers we get in oscilloscopes or spectrum analyzers where we can vary the x coordinate in order to find the respective y coordinates from the plots.

**Comment by anntzer** [comment]
You can already move the cursor using shift-left/shift-right.
If you want to draw a vertical line at the position of the cursor you may want to consider connecting your own event handler using `connect`.

**Comment by dwij2812** [comment]
Yes but if there can be some kind of flag option in the initialization function itself so it automatically pops on when hovered without pressing the shift keys would be more useful from UX point of view as most users who just see the window wont know about this unless specified so the developers can set the appropriate flags and whenever the user hovers the corresponding selections are made as intended.

**Comment by anntzer** [comment]
But isn't that what `hover=True` does?

**Comment by dwij2812** [comment]
No, that just shows the popup when we hover exactly on the line in the plot instead what i was asking was that we can hover anywhere on the graph and freeze x coordinates say so when we move the mouse cursor on the plot the x coordinate is used to interpret the y of the plot irrespective of the mouse cursor being in close proximity of the plotted lines

**Comment by anntzer** [comment]
Oh, I see.  That would be quite different from mplcursors current functionality, so I don't think it really belongs here; on the other hand you may want to have a look at e.g. https://matplotlib.org/gallery/misc/cursor_demo_sgskip.html which shows how to achieve something similar with matplotlib itself.

**Comment by dwij2812** [comment]
Yes, i was asking something of this sort along with the mplcursor popups which will be really great for many kinds of applications

**Comment by anntzer** [comment]
I think this is too far from what mplcursors provides, so currently I don't want to implement it here.
For example, this kind of functionality only makes sense if your x's are increasing (or decreasing), otherwise you have problems as to what to do when the curve "comes back" onto itself.  Obviously this is a very common case, but mplcursors is carefully designed not to make such assumptions and be more general.

**Comment by dwij2812** [comment]
Ok, Thanks
