### ISSUE TITLE
[Feature Request] Multiple Cursor Markers and Hover Functionality working Together

### ISSUE THREAD

**Issue by dwij2812** [anntzer/mplcursors#16]
In the next release can you make the Multiple Cursor option and the hover option able to work together as whenever we are trying to mark some points using multiple it is better to have a pop-up label hovering with the cursor that makes it easy to select the points on the plots.

Right now when we try to do the same it throws **ValueError: 'hover' and 'multiple' are incompatible**

**Comment by anntzer** [comment]
Sure, it's now allowed as of master.
Note that you'll get a *lot* of overlapping cursors from hovering, though.

**Comment by dwij2812** [comment]
I assume that it will be a lot helpful for marking the points as right now we just hover and use the values in the tool-tips of the matplotlib window to mark it but it would be a lot simpler with the hover and we can navigate easily.

**Comment by anntzer** [comment]
So is there anything else that needs to be done, or can this be closed?

**Comment by dwij2812** [comment]
Thanks a lot, Hoping we can soon get this in the upcoming release
