### ISSUE TITLE
TypeError: 'ContainerArtist' object is not subscriptable

### ISSUE THREAD

**Issue by nilswagner** [anntzer/mplcursors#17]
How can I fix the problem in my script
```
import string
import matplotlib.pyplot as plt
import mplcursors

fig, ax = plt.subplots()
ax.bar(range(9), range(1, 10), align="center")
labels = string.ascii_uppercase[:9]
ax.set(xticks=range(9), xticklabels=labels, title="Hover over a bar")

cursor = mplcursors.cursor(hover=True)
@cursor.connect("add")
def on_add(sel):
    x, y, width, height = sel.artist[sel.target.index].get_bbox().bounds
    sel.annotation.set(
        text="{}: {}".format(x + width / 2, height),
        position=(0, 20))
    sel.annotation.xy = (x + width / 2, y + height)

plt.show()
```

**Comment by nilswagner** [comment]
import string
import matplotlib.pyplot as plt
import mplcursors

fig, ax = plt.subplots()
ax.bar(range(9), range(1, 10), align="center")
labels = string.ascii_uppercase[:9]
ax.set(xticks=range(9), xticklabels=labels, title="Hover over a bar")

cursor = mplcursors.cursor(hover=True)
@cursor.connect("add")
def on_add(sel):
    x, y, width, height = sel.artist[sel.target.index].get_bbox().bounds
    sel.annotation.set(
        text="{}: {}".format(x + width / 2, height),
        position=(0, 20))
    sel.annotation.xy = (x + width / 2, y + height)

plt.show()

**Comment by nilswagner** [comment]
import string
import matplotlib.pyplot as plt
import mplcursors

fig, ax = plt.subplots()
ax.bar(range(9), range(1, 10), align="center")
labels = string.ascii_uppercase[:9]
ax.set(xticks=range(9), xticklabels=labels, title="Hover over a bar")

cursor = mplcursors.cursor(hover=True)
@cursor.connect("add")
def on_add(sel):
    x, y, width, height = sel.artist[sel.target.index].get_bbox().bounds
    sel.annotation.set(
        text="{}: {}".format(x + width / 2, height),
        position=(0, 20))
    sel.annotation.xy = (x + width / 2, y + height)

plt.show()

**Comment by anntzer** [comment]
Thanks for the report.  This should be fixed as of master now.

**Comment by nilswagner** [comment]
Thank you very much. How can I annotate the labels in my example? BTW, the arrow head jumps to the top of each part in the stacked column using mplcursor, whereas the old datacursor shows a smooth behaviour.

**Comment by anntzer** [comment]
Not sure what you mean, especially about the "smooth behavior"?
You set your annotation to (0, 20) but that's out of the axes, (0, 10) seems more reasonable.

**Comment by nilswagner** [comment]
Smooth means that the arrowhead can have an arbitrary position wrt to the stacked column bar.
How can I use the labels 'Men' and 'Women' in my annotations?

**Comment by nilswagner** [comment]
![mplcursor](https://user-images.githubusercontent.com/5382885/64866769-62792880-d63c-11e9-84e4-98843f5b64a4.gif)

**Comment by anntzer** [comment]
something like
```
mens = ax.bar(labels, men_means, width, label='Men')
womens = ax.bar(labels, women_means, width, bottom=men_means, label='Women')

ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.legend()

cursor = mplcursors.cursor(hover=True)
@cursor.connect("add")
def on_add(sel):
    labels = {mens: "Mens", womens: "Womens"}
    sel.annotation.set(text=labels[sel.artist])
```
works

**Comment by nilswagner** [comment]
Thank you very much. Can you create a new release?

**Comment by anntzer** [comment]
I'm waiting for the fedora package maintainer to confirm that master works for them, as they need a new release too -- hopefully this should be resolved soon.
Can this be closed?
