### ISSUE TITLE
Clicking on invisible lines still evinces an annotation

### ISSUE THREAD

**Issue by eBardieCT** [anntzer/mplcursors#18]
I'm porting a graphing tool (https://gitlab.com/eBardieCT/topplot/tree/ebardie/matplotlib) from using gnuplot to mpl. topplot implements toggling the visibility of lines by clicking on their legend lines.

It also makes use of mplcursors, so thanks BTW :), and I have found that even when a line is invisible, clicking where it would be displayed still leads to mplcursors displaying an annotation.

This trivial patch against mplcursors v0.3 resolves the problem for my use case, though you may wish to extend it to cover other potentially relevant artists.

```
--- _pick_info.py       2019-10-25 14:47:59.020688282 +0100
+++ _pick_info.py.new   2019-10-25 14:47:55.248639568 +0100
@@ -275,6 +275,9 @@
     # No need to call `line.contains` as we're going to redo the work anyways
     # (also see matplotlib/matplotlib#6645, though that's fixed in mpl2.1).

+    if artist.get_visible() == False:
+        return None
+
     # Always work in screen coordinates, as this is how we need to compute
     # distances.  Note that the artist transform may be different from the axes
     # transform (e.g., for axvline).
```

Thanks again,
Jonathan

**Comment by anntzer** [comment]
Thanks for the report.  c97ed24 should handle all artists at once.
Closing, but feel free to ping for reopen if this doesn't suffice.
