### ISSUE TITLE
Clicking on a legend in front of a line evinces an annotation

### ISSUE THREAD

**Issue by eBardieCT** [anntzer/mplcursors#19]
Even with the pick and click event callbacks always returning ```True, dict()```, when a line is underneath a legend, clicking on the legend at a point over the line still passes the event on to mplcursors (after processing it as a pick event and then a click event in the main application). 

Have I missed something in my setup or usage? Is this fixable within mplcursors? Or does this need addressing at the mpl level?

Regards,
Jonathan

**Comment by anntzer** [comment]
There is currently no mechanism in Matplotlib to know whether an event has already been handled (or even to ensure the order in which various handlers handle an event) -- there are actually a few places in the mpl tracker mentioning this as a feature request.
In your case, if you are attaching your own event handlers, you may be able to e.g. set an additional, custom flag on the event object, and add a mplcursors handler (`.connect("add", ...)` checking that flag, but it may be a bit messy (for example, if mplcursors happens to go first, then you may need to also check that in your "other" handler and remove the annotation, perhaps?  haven't thought about the nitty gritty details).

**Comment by eBardieCT** [comment]
Thanks for the suggestion Antony, it works :)

mplcursors seems to come last in the queue, which would make sense it being lower in the z-order.

The application specific code given below works for me, so I'll post it here to provide an example for others to draw upon if needs be.

My app has a Figman class which keeps track of various figure related goings on. When graphs are being constructed they can call the following function to enable mplcursors' annotations for an axis.

```
def add_annotations(figman, ax):
  if "mplcursors" in sys.modules:
    c = mplcursors.Cursor(hover=False, multiple=True, artists=tuple(ax.get_lines()))

    def on_add(sel):
      # Convert from data co-ords to display co-ords
      x, y = ax.transData.transform(tuple(sel.target))

      # Cycle through axes' legends checking for hits
      fake_event = mpl.backend_bases.MouseEvent("dummy", figman.fig.canvas, x, y)

      for legend in figman.get_legends():
        result, _ = legend.contains(fake_event)

        # Remove sel on hit
        if result:
          c.remove_selection(sel)

    c.connect("add", on_add)
```

**Comment by anntzer** [comment]
Looks reasonable, thanks for sharing your solution!
