### ISSUE TITLE
How do I set 'enabled' value?

### ISSUE THREAD

**Issue by jorgesmok** [anntzer/mplcursors#2]
I'm playing around with your cursors, I'm trying to make it work like a 'two points difference', where the user selects 2 points from a line and gets an annotation showing the x values difference. I want to manually set the enabled value of one cursor's instance but I can't, I tried setting its value with `cursor.enabled(value)` but it seems enabled is a property and not a method.

**Comment by anntzer** [comment]
You should be able to do `cursor.enabled = value`.
For your goal (drawing the distance between two points) you could also use `multiple=True` and add a handler when the number of selections is 2.  Let me know if you'd like a more detailed example, I'm happy to help.

**Comment by jorgesmok** [comment]
I hadn't thought I could just access that property like that. I was using it as a function setter because I read it on _mplcursors.py. 

Thanks for that idea! I followed your suggestion and now I almost got it done. The only thing missing is that I want just one bbox showing the distance and two arrows connecting the bbox and the selected points. 

I got rid of one of the selections' bbox by setting to 'None' its value and its text to '"". Now I just have to connect the arrow of this selection with the bbox of the other selection, so I have to set the position of one selection's annotation equal to the other one, but since the textcoords are "offset points", they are relative to the xy value of each annotation. So I thought setting the textcoords to 'data' and put the bbox at a fixed position. 
```
	def distance_manager(self, sel):
		if len(self.cursor_distance.selections) == 1:
			return
		if len(self.cursor_distance.selections) >= 2:
			for selection in self.cursor_distance.selections[:-2]:
				self.cursor_distance.remove_selection(selection)
			sel1 = self.cursor_distance.selections[0]
			y1 = sel1.target[0]
			y2 = sel.target[0]
			diferencia = np.absolute(y1-y2)
			sel.annotation.set(text='Diferencia angular = {:.2f} °'.format(diferencia))
			sel1.annotation.set_bbox(None)
			sel1.annotation.set(text='')
			sel.annotation.textcoords = 'data'
			sel1.annotation.textcoords = 'data'
			sel.annotation.set(position=(0, 0.3))
			sel1.annotation.set(position=(0, 0.3))
```

But for some reason it isn't working, it correctly eliminates the sel1's bbox and its text, but its arrow isn't connecting to the other bbox, it's connecting to (0, 0.3) relative to the picked point, same goes for the other arrow, it places the bbox at (0, 0.3) relative to its picked point, instead of placing it at the fixed (0, 0.3) data coords.

**Comment by anntzer** [comment]
For this kind of customization I'd just remove the selection annotations and create a new annotation from scratch, something like
```
from matplotlib import pyplot as plt
import mplcursors
import numpy as np


fig, ax = plt.subplots()
ax.plot(np.random.rand(10), np.random.rand(10), "o")
ax.set(xlim=(0, 1), ylim=(0, 1))
cursor = mplcursors.cursor(multiple=True)

@cursor.connect("add")
def distance_manager(sel):
    if len(cursor.selections) == 2:
        s0, s1 = cursor.selections
        x0, y0 = s0.target
        x1, y1 = s1.target
        for sel in cursor.selections:
            cursor.remove_selection(sel)
        ax.annotate("distance: {:.2f}".format(abs(x1 - x0)),
                    xy=((x1 + x0) / 2, (y1 + y0) / 2),
                    xytext=(.5, .5), ha="center", va="center",
                    arrowprops={"arrowstyle": "->"},
                    bbox={"boxstyle": "round,pad=.5",
                          "fc": "y", "alpha": .5, "ec": "k"})
        # You may want to keep a reference to the annotation,
        # so that you can remove it later.

plt.show()
```

Let me know if this helps or if it's unclear.

**Comment by anntzer** [comment]
I'm closing the issue as the original question has been handled, but feel free to ask more questions here.

**Comment by jorgesmok** [comment]
Thanks for your help, I could build up from there to get the thing I wanted :)
