### ISSUE TITLE
Basic examples not working in Jupyter Lab

### ISSUE THREAD

**Issue by gioarma** [anntzer/mplcursors#23]
Hi, I tried to run two of the example codes ('basic' and 'hover'), but they don't seem to work. I just get a static image of the plot, without any error.
The package version is 0.3, installed with conda.
I'm using Jupyter Lab (version 1.2.4) on Chrome (macOS High Sierra)
I just downloaded the jupyter notebook examples and run them, without changing anything.
Any idea of what could be the problem?
Thanks

**Comment by story645** [comment]
Works for me (weird coloring is likely cause I used an internet mp4-gif convertor):
>Jupyterlab 2.0.1
CPython 3.8.2
IPython 7.13.0

matplotlib 3.2.0
ipympl 0.5.3
ipywidgets 7.5.1
mplcursors 0.3.post18+ga4b48fb


![JupyterLab-Mozilla-Firefox-2020-03-11-22-45-41_Trim](https://user-images.githubusercontent.com/1300499/76482718-60293880-63eb-11ea-81bc-83eb2d1ae8fb.gif)
![JupyterLab-Mozilla-Firefox-2020-03-11-22-44-46_Trim](https://user-images.githubusercontent.com/1300499/76482721-61f2fc00-63eb-11ea-8d8e-f5f6a9c96f7a.gif)

**Comment by gioarma** [comment]
After updating all packages I still didn't see any change.
However I noticed from your gifs that you are using jupyter-matplotlib, so I tried so substitute `%matplotlib inline` with `%matplotlib widget` and now it works. Then I would suggest to change the Jupyter example making this substitution.

Anyway, now I have another problem. The response is very slow and the graph disappears for a moment everytime I click on a point. As opposed to your gif I see that in my case Python 3 is busy even when I just move the mouse on the graph. Here's a screenshot (I don't know why there are shades where the cursor used to be, must be a problem with the gif converter again, I don't actually see this on mu screen): 
![Screenshot](https://user-images.githubusercontent.com/59478987/76501987-867ac280-6443-11ea-871a-00841ec2fc86.gif)

**Comment by story645** [comment]
>substitute %matplotlib inline with %matplotlib widget and now it works
Yes, the inline backend is only for static visualizations whereas the widget backend is the recommended jupyter backend for interactive visualizations. 

> Then I would suggest to change the Jupyter example making this substitution.
Can you please link to this example because I'm having trouble finding it.

**Comment by gioarma** [comment]
The notebook version of this example: https://mplcursors.readthedocs.io/en/stable/examples/hover.html#sphx-glr-examples-hover-py

**Comment by anntzer** [comment]
I will remove the jupyter notebook links once this becomes possible in sphinx-gallery (https://github.com/sphinx-gallery/sphinx-gallery/issues/622).

**Comment by anntzer** [comment]
The links are now removed from the latest docs build: https://mplcursors.readthedocs.io/en/latest/examples/basic.html
(you may need to reload the CSS as sphinx-gallery changed their CSS file).

Closing, but feel free to request more info if needed.

**Comment by paulaberry** [comment]
I am having the same issue - the plots are only showing up as static in a clean notebook on a fresh JupyterLab install. I have tried `%matplotlib inline`  `%matplotlib widget`, and just leaving out the cell magic all together.

Here's my package versions:
Python 3.8.8
Jupyter Lab 3.2.9
iPython 7.22.0
matplotlib 3.3.4
ipympl 0.8.8
ipywidgets 7.6.3
mplcursors 0.5.1

here is the code I'm running in a Jupyter lab .ipynb file:

```
import matplotlib.pyplot as plt
import numpy as np
import mplcursors

data = np.outer(range(10), range(1, 5))

fig, ax = plt.subplots()
lines = ax.plot(data)
ax.set_title("Click somewhere on a line.\nRight-click to deselect.\n"
             "Annotations can be dragged.")

mplcursors.cursor(lines)  # or just mplcursors.cursor()

plt.show()
```
All that is produced is a static plot, no annotations on over or click.

**Comment by story645** [comment]
it works for me once I got ipywidgets working - I had to rebuild the jupyterlab extensions

**Comment by ZaneBartlett1** [comment]
Found this article https://towardsdatascience.com/tooltips-with-pythons-matplotlib-dcd8db758846 that talks about needing to use `%matplotlib widget`, which fixed my issue, and I didn't find anywhere else so I figured I'd put this here.

**Comment by camillejmora** [comment]
I am on a MacOS system and when I installed [ipympl](https://matplotlib.org/ipympl/installing.html) using a conda environment, the code (below) worked when I opened a Jupyter notebook. Note, I launced Anaconda via my terminal since for some reason it wouldn't open via conda using the information [here](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html). Hopefully it works for you!

```
import matplotlib.pyplot as plt
import numpy as np
import mplcursors

data = np.outer(range(10), range(1, 5))

fig, ax = plt.subplots()
lines = ax.plot(data)
ax.set_title("Click somewhere on a line.\nRight-click to deselect.\n"
             "Annotations can be dragged.")

mplcursors.cursor(lines)  # or just mplcursors.cursor()

plt.show()
```
