### ISSUE TITLE
Moving cursor left or right doesn't work with polar plots

### ISSUE THREAD

**Issue by jorgesmok** [anntzer/mplcursors#3]
Hi, so far this package has been awesome for an antenna design GUI I'm building, it makes heavy use of plots so I implement cursors everywhere. I recently tried to add a mplcursor to a matplotlib's polar plot and I want to use the 'left' and 'right' bindings in order to move along the trace. However, when I press the assigned keys to 'left' and 'right', the selection doesn't move to the next data point, instead, it blinks and stays in the same position. I've tried this function with normal cartesian plots and it works perfectly, but don't know what happens with polar plots.

**Comment by anntzer** [comment]
The issue should be fixed now.  Please let me know if it works for you.

I would appreciate if you could provide a link to your GUI, I may consider (possibly) adding to the docs a list of users of the package.

**Comment by jorgesmok** [comment]
Works like a charm now! I would be pleased of providing you the link when I finish it, it's my undergraduate thesis and it's not finished yet.
