### ISSUE TITLE
Linked artists    lines and text

### ISSUE THREAD

**Issue by 5PvM4rm** [anntzer/mplcursors#31]
I tried to implement linked artists for the graph below:
![image](https://user-images.githubusercontent.com/75709773/103326332-245c6f80-4a0d-11eb-9c82-66ecebf90f13.png)

It gave me a **_TypeError: cannot unpack non-iterable Annotation object matlibplot annotate_** error.   Both the linear element and the annotation text on the right have the same  "label" attached.  

I was hoping to be able to click on a linear element and have the associated annotation text and the linear element highlighted and visa versa.

**Comment by anntzer** [comment]
Please include a repro.  (See http://sscce.org/.)

**Comment by 5PvM4rm** [comment]
Hi Antony,

Thanks for your quick reply.   Rather than listing the error I should have
asked if what I was trying to do, linking the annotation to the
lines, could work.   If so, I'll create a simple scaled down version.

Thanks again.
Peter

**Comment by anntzer** [comment]
See e.g. `examples/paired_highlight.py` for the kind of things that's possible.

**Comment by 5PvM4rm** [comment]
Pleas see below a small py program that produces the "TypeError: cannot unpack non-iterable Annotation object"   I'm pretty new at coding and this might not even be a problem related to mplcursors.  Any suggestions will appreciated.
 No problems if I place dot, but I get the errors with text or annotation


import numpy as np
import matplotlib.pyplot as plt
import mplcursors
def main():
    fig, axes = plt.subplots()
    lines = []
    texts=[]
    for i in range(5):
        llabel='line '+str(i)
        line, = axes.plot((i + 1) * np.arange(10),label=llabel)
        lines.append(line)
        Last_y=(i + 1) * np.arange(10)
        text, =axes.annotate(' '+llabel, xy=(9.00,Last_y[-1]), xytext=(3,0), color='black', 
             textcoords="offset points",
            size=10, va="center" ,zorder=40,label=llabel )
        texts.append(text)
    cursor = mplcursors.cursor( highlight=True)
    pairs = dict(zip(lines, texts))
    pairs.update(zip(texts, lines))
    @cursor.connect("add")
    def on_add(sel):
        sel.annotation.set_text(sel.artist.get_label())
    plt.show()
if __name__ == "__main__":
    main()

**Comment by 5PvM4rm** [comment]
Sorry I didn't mean to close it.
Peter

**Comment by anntzer** [comment]
Your problem does not occur in a line of code related to mplcursors (indeed, you can delete every line related to mplcursors and still get the same error), so I would suggest you ask for help in a more general forum, such as https://discourse.matplotlib.org/.
