### ISSUE TITLE
Using mplcursors to toggle visibility of line?

### ISSUE THREAD

**Issue by agpr141** [anntzer/mplcursors#33]
Hi- I have just found mplcursors and it is very useful for a task I am trying to do. I also wonder, is it possible to toggle the visibility of a selected line by (for example) right clicking on a line in a plot? Something like:

def right_click(event):
    if event.button == 1:
        mplcursors.cursor(ax, **visbility=False**)
fig.canvas.callbacks.connect('button_press_event', right_click)

Thanks!

**Comment by anntzer** [comment]
If I understand your request correctly, you can use a callback (https://mplcursors.readthedocs.io/en/stable/#customization) to set the visibility (https://matplotlib.org/3.3.4/api/_as_gen/matplotlib.artist.Artist.set_visible.html) of the artist.

**Comment by agpr141** [comment]
Thanks for the direction- would that look something like this? (sorry to ask, just at the end of my tether here and don't know how to get this working!) Thanks in advance

`import mplcursors
import matplotlib.pyplot as plt
import numpy as np

array = np.array([[1,3,1], [1.5,3,2], [0.9, 2.9, 1]]).T
non_blinks = []
fig, ax = plt.subplots()
ax.plot(array, picker=5)

def left_click(event):
    if event.button == 1:
        mplcursors.cursor(ax, highlight=True)

**def right_click(event):
    if event.button == 3:
        mplcursors.cursor(ax)
        non_blinks.append(ax.lines.index(event.artist))**

fig.canvas.callbacks.connect('button_press_event', left_click)
**fig.canvas.cursor.connect('right_click', lambda sel: sel.artist.set_visible(not sel.artist.get_visible())**
plt.show()`
