### ISSUE TITLE
Setup fails with proxy

### ISSUE THREAD

**Issue by kb-** [anntzer/mplcursors#35]
Mplcursors setup.py makes a request without using proxy parameter, which hangs install.
Fails: `python -m pip install mplcursors -v --proxy=proxyaddress.fr:3131`
Successful workaround: `python -m pip install setuptools_scm mplcursors -v --proxy=proxyaddress.fr:3131` 

`(PI) C:\Users\f30154\Documents\Python\PI>python -m pip install mplcursors -v --proxy=proxyaddress.fr:3131
Using pip 21.0 from C:\Users\f30154\Documents\Python\PI\PI\lib\site-packages\pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: C:\Users\f30154\AppData\Local\Temp\pip-ephem-wheel-cache-d8h3rv6d
Created temporary directory: C:\Users\f30154\AppData\Local\Temp\pip-req-tracker-6_p_32qx
Initialized build tracking at C:\Users\f30154\AppData\Local\Temp\pip-req-tracker-6_p_32qx
Created build tracker: C:\Users\f30154\AppData\Local\Temp\pip-req-tracker-6_p_32qx
Entered build tracker: C:\Users\f30154\AppData\Local\Temp\pip-req-tracker-6_p_32qx
Created temporary directory: C:\Users\f30154\AppData\Local\Temp\pip-install-6c84erdq
1 location(s) to search for versions of mplcursors:
* https://pypi.org/simple/mplcursors/
Fetching project page and analyzing links: https://pypi.org/simple/mplcursors/
Getting page https://pypi.org/simple/mplcursors/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Looking up "https://pypi.org/simple/mplcursors/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/mplcursors/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/70/bb/4ae383a3cace4ffa23e185e94c24e9084c45ed933071c561947750a18dd3/mplcursors-0.1-py3-none-any.whl#sha256=ea409e05530a21b32db38a0ac0bafe58ae20c5f35ab801cf86f5bed67bde1e50 (from https://pypi.org/simple/mplcursors/), version: 0.1
  Found link https://files.pythonhosted.org/packages/89/07/b27ea2efbed0a7c85d28b74ace5150f7ee90be26b85908ba621d748e8bb3/mplcursors-0.2-py3-none-any.whl#sha256=1f3912d3991b4830396281a71fadbdafb9524275c1db4449aa5c5e9bab913180 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.4), version: 0.2
  Found link https://files.pythonhosted.org/packages/4e/97/d05cc88fb9fd79274154351e343d3a9f2fa741875953393f7f53696271a5/mplcursors-0.2.tar.gz#sha256=67fbbc5c7ea979c223baf01df55e3cab425f71d3fb96ed100686873ddf3ae786 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.4), version: 0.2
  Found link https://files.pythonhosted.org/packages/92/e2/536d2391dee7ef93e298435cb79a2baf4057f17fa13a5213d60eae0b4029/mplcursors-0.2.1-py3-none-any.whl#sha256=59b900ab360fc0ec4edf3fbd49f3f0018615d89faf09d97442c3a1d93d431497 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.4), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/cd/80/00d6b703d738322bf39ccefc97b1cdf8b1a16a5552000b6738b224bc5f01/mplcursors-0.2.1.tar.gz#sha256=dd975ffd645e3a9c84087a7285bb3b07b4ef42d4e874fcc74c2f98ab8ecf01e1 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.4), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/5e/5f/3853620d0e04b893318e3ba20c0da1f24b56d5f2a08f7a2adf5ba86ea1c0/mplcursors-0.3-py3-none-any.whl#sha256=8039055ad59c2f8f0b36600117426bf80123397ceb8164fe9894c5a6009ac641 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.6), version: 0.3
  Found link https://files.pythonhosted.org/packages/eb/49/3d22a1e0da0c70fc04ab92960f6641823aed46f1193aa67b689e8e509931/mplcursors-0.3.tar.gz#sha256=0e32c1c613f883a436d53ad658c0377abd84ac0235d940c135e11c94a1baefd0 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.6), version: 0.3
  Found link https://files.pythonhosted.org/packages/89/af/01c4bd4c6bf75bc1692b8b4181e71cf98197bd3e4750b9a0d9f584507d92/mplcursors-0.4.tar.gz#sha256=a8646437e35acab37dc07ef0fca6bc8f66ffbae99d4d5a441ea254a94aed1d24 (from https://pypi.org/simple/mplcursors/) (requires-python:>=3.6), version: 0.4
Given no hashes to check 8 links for project 'mplcursors': discarding no candidates
Collecting mplcursors
  Created temporary directory: C:\Users\f30154\AppData\Local\Temp\pip-unpack-bvt6tji4
  Getting credentials from keyring for files.pythonhosted.org
  Looking up "https://files.pythonhosted.org/packages/89/af/01c4bd4c6bf75bc1692b8b4181e71cf98197bd3e4750b9a0d9f584507d92/mplcursors-0.4.tar.gz" in the cache
  Current age based on date: 224
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 224
  Using cached mplcursors-0.4.tar.gz (86 kB)
  Added mplcursors from https://files.pythonhosted.org/packages/89/af/01c4bd4c6bf75bc1692b8b4181e71cf98197bd3e4750b9a0d9f584507d92/mplcursors-0.4.tar.gz#sha256=a8646437e35acab37dc07ef0fca6bc8f66ffbae99d4d5a441ea254a94aed1d24 to build tracker 'C:\\Users\\f30154\\AppData\\Local\\Temp\\pip-req-tracker-6_p_32qx'
    Running setup.py (path:C:\Users\f30154\AppData\Local\Temp\pip-install-6c84erdq\mplcursors_179baf302df143bb8ed04e400e95aea3\setup.py) egg_info for package mplcursors
    Created temporary directory: C:\Users\f30154\AppData\Local\Temp\pip-pip-egg-info-jq4ijp36
    Running command python setup.py egg_info
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DAF4769910>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools-scm/`

**Comment by anntzer** [comment]
This looks like a problem on pip's side, e.g. https://github.com/pypa/pip/issues/3478 perhaps.
