### ISSUE TITLE
Can you use mplcursor hover while zooming in?

### ISSUE THREAD

**Issue by JayVaz18** [anntzer/mplcursors#36]
I'm trying to use mplcursor hover when zooming in using Matplotlib but the artist is disappearing. It also never comes back even after zooming back out...

Is there any way around this? Because it would be very helpful if we can zoom in and still maintain the hover option or at the very least have it come back when zooming out.

**Comment by anntzer** [comment]
Not sure what you exactly want, but the interaction with zooming that you mention is probably the `widgetlock.locked()` check at https://github.com/anntzer/mplcursors/blob/efe8a01d29fa298d63dd63d40b1487c27f2bc9d2/lib/mplcursors/_mplcursors.py#L575

**Comment by JayVaz18** [comment]
So here's an an unzoomed image of the plot I have in which the hover feature of mplcursor works: 

<img width="490" alt="Screen Shot 2021-05-18 at 4 06 05 PM" src="https://user-images.githubusercontent.com/72083618/118716727-29229400-b7f3-11eb-87fe-e99b7d2c7327.png">

Then, when I zoom in and hover over any of the rectangles in the last three subplots, no hover annotation occurs:

<img width="491" alt="Screen Shot 2021-05-18 at 4 06 36 PM" src="https://user-images.githubusercontent.com/72083618/118716794-3c356400-b7f3-11eb-8f8c-97de62eeb11e.png">

Then, when I zoom back out, I'm not able to see any annotation anymore when I hover over the rectangles. Interestingly, my cursor starts as an arrow like usual but then once I zoom in and out, never goes back to that. My cursor becomes only what I select in the interactive Matplotlib widget such as zoom or shifting. So, I'm wondering if I can enable mplcursors to keep showing the annotation on hover when zooming in and out.

**Comment by anntzer** [comment]
Can you provide a minimal reproducible example?

**Comment by JayVaz18** [comment]
I have much more code and customization for the annotation than this but this is a very simple example:

`import matplotlib.pyplot as plt
import numpy as np
import mplcursors
np.random.seed(42)

fig, ax = plt.subplots()
ax.scatter(*np.random.random((2, 26)))
ax.set_title("Mouse over a point")

mplcursors.cursor(hover=True)

plt.show()`

I can easily hover over any point and get the annotation right after running as seen below:

<img width="2048" alt="Screen Shot 2021-05-19 at 9 19 56 AM" src="https://user-images.githubusercontent.com/72083618/118819785-abf32f80-b883-11eb-8340-5a7e894cc9b9.png">

However, when I zoom in using the pan button in the interactive window, I can no longer hover over the points and get annotation (my cursor is directly on a point I zoomed in on. 

<img width="2048" alt="Screen Shot 2021-05-19 at 9 20 32 AM" src="https://user-images.githubusercontent.com/72083618/118819882-c4fbe080-b883-11eb-94fb-f7d916d5f662.png">

Also, when I zoom back out, I no longer can hover over any points to generate a label. It's as if mplcursor functionality disappears. Is there a way so I can continue showing annotation on hover when zooming in and out?

**Comment by anntzer** [comment]
Ah, I see.  This is fixed as of master, thanks for the report.

**Comment by JayVaz18** [comment]
What? How do I fix it..

**Comment by JayVaz18** [comment]
Got it, thanks!
