### ISSUE TITLE
zorder not respected

### ISSUE THREAD

**Issue by marv42** [anntzer/mplcursors#37]
Hey,
i am not sure, if i should be doing it differently.
But i am encountering the issue "annotation does not respect zorder / it is always under one of the axes".

Here is an sscce:

```python
import mplcursors
from matplotlib import pyplot as plt

figure, axis_1 = plt.subplots()
axis_2 = axis_1.twinx()
line_1 = axis_1.plot([1, 2])
line_2 = axis_2.plot([2, 1])
lines = [line for a in figure.axes for line in a.lines]
cursor = mplcursors.cursor(lines, hover=True)  # annotation_kwargs={'zorder': 9999} throws "multiple 'zorder' values"
@cursor.connect("add")
def _(sel):
    sel.annotation.get_bbox_patch().set(alpha=1, zorder=9999)
plt.show()
```

It would be great, if you could point me to some resolution or a workaround...

**Comment by anntzer** [comment]
Thanks for the report.  This should be fixed now as of master.
