### ISSUE TITLE
mplcursors in plots with several scatter objects: only the last labels list is considered

### ISSUE THREAD

**Issue by Vital-Fernandez** [anntzer/mplcursors#38]
First of all, thank you for this great library. 

I wonder if I could get some sugestions on how to use mplcursors in plots with several ax.scatter  objects. This is an example:

```
import numpy as np
import matplotlib.pyplot as plt
import mplcursors

x_1 = np.array([1, 2, 3])
y_1 = x_1
labels1 = ['a', 'b', 'c']

x_2 = np.array([1, 2, 3, 4])
y_2 = x_2 * 2
labels2 = ['d', 'e', 'f', 'g']

x_values = [x_1, x_2]
y_values = [y_1, y_2]
labels = [labels1, labels2]

fig, ax = plt.subplots(figsize=(10, 10))

for i, x in enumerate(x_values):
    data_scatter = ax.scatter(x, y_values[i], label=f'{i}')
    mplcursors.cursor(data_scatter).connect("add", lambda sel: sel.annotation.set_text(labels[i][sel.target.index]))

ax.legend()
plt.show()
```

If you click on the data points you will notice that the second label list (labels2) is show on both data sets. 

Thanks for any advice

**Comment by anntzer** [comment]
Thanks for your appreciation.
This is a standard Python trap; you need to write e.g. `lambda sel, i=i: sel.annotation.set_text(...)` (note the `i=i`).  See https://docs.python-guide.org/writing/gotchas/#late-binding-closures for an explanation.
