### ISSUE TITLE
Having different labels for different plots on the same axes

### ISSUE THREAD

**Issue by ese-jdm418** [anntzer/mplcursors#39]
Hi,

I am currently wanting to create a 3D scatter plot with matplotlib in python to try and show stock and flow data in 3D. The interactive labels of mplcursors are really good, however, I have hit a wall with something I would like to do so asking for help here.

I am wanting to plot 2 or more scatter plots on the same axes, e.g. some dots represents stocks and some other ideas. I want these to have different style attributes like marker style, colour and size and so on. However, I have become a bit stuck when trying to set different labels for the different scatter plots. It keeps adding the labels and making them overlap which I don't want. Here is my current code:
```python
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x_stock =[0, 1, 2]
y_stock =[0, 0, 0]
z_stock =[1, 1, 1]

x_process =[0, 0, 0]
y_process =[1, 0, 0]
z_process =[2, 0, 0]

labels = ["Stock_1", "Stock_2", "Stock_3"]
labels_2 = ["Process_1", "Process_2", "Process_3"]

ax.scatter(x_stock, y_stock, z_stock, c='r', marker='o')

mplcursors.cursor(ax).connect("add", lambda sel: sel.annotation.set_text(labels[sel.target.index]))
ax.scatter(x_process, y_process, z_process, c="g", marker="o", s=200)


mplcursors.cursor(ax).connect("add", lambda sel: sel.annotation.set_text(labels_2[sel.target.index]))

a1 = Arrow3D([0, 1], [0, 0], [1, 1], mutation_scale=20, lw=3, arrowstyle="-|>", color="k", connectionstyle="arc3,rad=.5")
ax.add_artist(a1)

plt.axis("off")
plt.show()
```

I would like it if the first scatter plot only had the stock labels and the second only the process labels. Any help would be greatly appreciated.

John.

**Comment by anntzer** [comment]
You can just pass whatever artists you want to each `Cursor` instantiation, e.g.
```python
pc1 = ax.scatter(x_stock, y_stock, z_stock, c='r', marker='o')
mplcursors.cursor(pc1).connect("add", lambda sel: sel.annotation.set_text(labels[sel.target.index]))
pc2 = ax.scatter(x_process, y_process, z_process, c="g", marker="o", s=200)
mplcursors.cursor(pc2).connect("add", lambda sel: sel.annotation.set_text(labels_2[sel.target.index]))
```

**Comment by ese-jdm418** [comment]
Thank you for the very quick reply, it has worked thank you!

May I just ask another quick question however, is there anyway to add labels to the arrow I have added near the end of the code. To be able to plot a curved arrow in 3D , I have altered the FancyArrowPatch in matplotlib using this code:

class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

Thank you again and I hope there is maybe a solution to be able to add a label to the arrow as well.

John.

**Comment by anntzer** [comment]
You can register a custom specialization for `_pick_info.compute_pick` (see e.g. https://github.com/anntzer/mplcursors/blob/master/lib/mplcursors/_pick_info.py#L276, see also https://docs.python.org/3/library/functools.html#functools.singledispatch).  There's no public API to access that for now.

**Comment by ese-jdm418** [comment]
Thank you for the help and links. I understand what I was asking about is quite specialized as I altered a class. I will have a look at what you have supplied though I normally use Python for quite low level uses and basic data analysis so if you do not mind if I struggle I may ask again later. Thank you for the help so far again.

John.

**Comment by anntzer** [comment]
No worries, happy to help.
