### ISSUE TITLE
index error displaying a custom label for each individual point

### ISSUE THREAD

**Issue by dbellistri00** [anntzer/mplcursors#40]
Hi, 
Great library!
I tried to run the example "[Displaying a custom label for each individual point](https://mplcursors.readthedocs.io/en/stable/examples/labeled_points.html)" and it gives the following error;

**AttributeError: 'numpy.ndarray' object has no attribute 'index'**

I am using
-matplotlib                3.4.3
-mplcursors                0.4.post14+g213770b
-numpy                     1.19.5

Thanks!
Domenico

**Comment by anntzer** [comment]
The API has slightly changed as of master (https://github.com/anntzer/mplcursors/blob/master/CHANGELOG.rst#next), you'll need the corresponding example instead (https://mplcursors.readthedocs.io/en/latest/examples/labeled_points.html) if you are using the git HEAD.

**Comment by dbellistri00** [comment]
Thank you!
