### ISSUE TITLE
`sel.target.index` no longer works on master

### ISSUE THREAD

**Issue by nmearl** [anntzer/mplcursors#41]
I've updated my local version to the [current master](https://github.com/anntzer/mplcursors/commit/ccf76c2c67f8ae87cc0ff08e704e7d08041a96b4) and suddenly my annotations will not work when using `sel.target.index`.

**Comment by anntzer** [comment]
I know, this is an intended change (https://github.com/anntzer/mplcursors/commit/cc94ebb7cd039589c94482ae27306f97aae0491f): the rationale is that `index` should just be `sel.index`, which is way more discoverable, easier to document, and does not require doing weird things with ndarray subclasses to add custom attributes.

I guess I could have done a proper deprecation, though.  I'll consider that before making a new release.

**Comment by anntzer** [comment]
I pushed a deprecated backcompat layer on master; can you check whether it would have helped in your case?

**Comment by nmearl** [comment]
This works great, thanks @anntzer!
