### ISSUE TITLE
Module index missing from doc

### ISSUE THREAD

**Issue by maximeflya** [anntzer/mplcursors#44]
Hi!
In the previous version, I was able to use in my sphinx doc ``:mod:`mplcursors` `` link with sphinx.ext.intersphinx to point to the module's documentation in mine.

When checking `python3 -m sphinx.ext.intersphinx https://mplcursors.readthedocs.io/en/stable/objects.inv`
The link seems to not appear anymore

**Comment by anntzer** [comment]
Good catch.  Can you verify that /latest works?

**Comment by anntzer** [comment]
I'll wait a bit before doing a new release (perhaps a few days after mpl3.5 is out), in case anything else pops up.

**Comment by anntzer** [comment]
0.5.1 has been released.  Again, thanks for the report.
