### ISSUE TITLE
Anotations are kept after the graph is redrawed

### ISSUE THREAD

**Issue by eyalk11** [anntzer/mplcursors#46]
Hi, I have a problem.  Not sure it is your bug or not. 

To update the graph, I simply remove all the lines and add other lines.
This still keeps some rouge annotations present. 
The text update is 
```
sel.annotation.set_text(annotation_str)
```
( I do it under mutex with the cursor remove).

Before updating the graph I do (removed some checks): 

```
self.cursor.remove()
self.cursor.disconnect('add', cb=self.cb)
 for child in plt.gca().get_children():
            if isinstance(child, matplotlib.lines.Line2D):
                child.remove()
del self.cursor
```
Afterwards 
```
dt.plot.line(reuse_plot=True, ax=ar)

self.cursor = mplcursors.cursor(hover=True)
self.cb= self.cursor.connect('add', partial(show_annotation,cls=self,ax=ar,generation=self.generation))
```
I also tried removing using self.curosr.remove_selection , keeping all selection object to no avail. 

The thing is that I do those actions from possibly different threads. When it was the same thread it seemed to work. 

I tried keeping self.cursor. At this time, no annotation was present.

Do you know what is the problem? Thanks for the help!

**Comment by eyalk11** [comment]
I managed to treat it like so.

In the annotation callback function I provide a generation which is the current time I have created `self.cursor`  and my class. 
And if it is different then current generation I do remove_selection, but actually, it is related to a previous cursour object..
cursor.selections is empty. 

So, I do 
```
            with suppress(ValueError):
                sel.annotation.remove()
            for artist in sel.extras:
                with suppress(ValueError):
                    artist.remove()
```
And that solves it. But I still get: 

```
Traceback (most recent call last):
  File "C:\Users\ekarni\compare-my-stocks\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\ekarni\compare-my-stocks\venv\lib\site-packages\mplcursors\_mplcursors.py", line 567, in _on_hover_motion_notify
    self._on_select_event(event)
  File "C:\Users\ekarni\compare-my-stocks\venv\lib\site-packages\mplcursors\_mplcursors.py", line 615, in _on_select_event
    self.add_selection(pi)
  File "C:\Users\ekarni\compare-my-stocks\venv\lib\site-packages\mplcursors\_mplcursors.py", line 433, in add_selection
    or len(self.selections) > 1 and not self._multiple
  File "C:\Users\ekarni\compare-my-stocks\venv\lib\site-packages\mplcursors\_mplcursors.py", line 304, in selections
    raise RuntimeError("Annotation unexpectedly removed; "
RuntimeError: Annotation unexpectedly removed; use 'cursor.remove_selection' instead
```

The object wasn't removed..

**Comment by eyalk11** [comment]
Now I debug it and saw you don't delete the callbacks on remove! . It still had callback with generation 2 .

**Comment by anntzer** [comment]
- Matplotlib (and thus mplcursors) are absolutely not thread-safe, see https://matplotlib.org/stable/users/faq/howto_faq.html#work-with-threads, there's no guarantee whatsoever that anything will work with threads.
- Can you please provide a minimal self-contained example to reproduce the issue?

**Comment by eyalk11** [comment]
Thanks for the reply. It was solved at last. Apparently, it had some interaction with some other mpl_connect and mpl_disconnects I did. I am not sure why.
