### ISSUE TITLE
Disable showing the annotation when the same curve has been already selected

### ISSUE THREAD

**Issue by BarryLiu97** [anntzer/mplcursors#47]
Hi, I found when using ```multiple=True```, it would let us show the annotation of the same curve, even if this curve has already been selected and has an annotation. 
So I think it might be reasonable to avoid showing the same annotation of the same curve.

**Comment by anntzer** [comment]
You can add a callback to remove the selection if there's already another selection with the same artist, e.g.
```python
from pylab import *
import mplcursors

plot([1, 2]); plot([3, 4])
c = mplcursors.cursor(multiple=True)

@c.connect("add")
def remove_duplicates(sel):
    if len([s for s in c.selections if s.artist is sel.artist]) >= 2:
        c.remove_selection(sel)

show()
```

**Comment by BarryLiu97** [comment]
Hi, is there any way that I could show the newest annotation, not the old one?

**Comment by anntzer** [comment]
You can probably adjust the callback accordingly.  (The variety of possible behaviors is exactly why I provide a callback instead of individual APIs for each possible request.)
