### ISSUE TITLE
String indexing error

### ISSUE THREAD

**Issue by Vital-Fernandez** [anntzer/mplcursors#48]
Hello @anntzer and thank you for your library.

I have this issue which I cannot nail down. In this code, I want mplcursors to display a different text than the one in the legend:

```
import numpy as np
import matplotlib.pyplot as plt
import mplcursors

x_1 = np.array([1, 2, 3])
y_1 = x_1

x_2 = np.array([1, 2, 3, 4])
y_2 = x_2 * 2

x_values = [x_1, x_2]
y_values = [y_1, y_2]
labels_mplcursors = ['m = 1', 'm = 2']
labels_legend = ['Dataset 1', 'Dataset 2']

fig, ax = plt.subplots(figsize=(10, 10))

container = {}
for i, x in enumerate(x_values):
    line = ax.plot(x, y_values[i], label=labels_legend[i])
    container[labels_mplcursors[i]] = line

for label, line in container.items():
    mplcursors.cursor(line).connect("add", lambda sel, labels_group=label: sel.annotation.set_text(labels_group[sel.index]))

ax.legend()
plt.show()
```
Clicking on the lines brings this issue:

`TypeError: string indices must be integers
`
My guess is that it is using the data or the matplotlib line objects ax plot to loop through something... I wonder if you could please point me in the right direction. 

Thank you

**Comment by anntzer** [comment]
index is the position of the selection *within* the artist; you probably want to do something with `sel.artist` (e.g. a reverse lookup into container).
