### ISSUE TITLE
Annotation only shown Y value when hovering.

### ISSUE THREAD

**Issue by liudonghua123** [anntzer/mplcursors#57]
I have a scatter graph, the x values are some timestamp ints, and y values are some floats, I read the docs on https://mplcursors.readthedocs.io/en/stable/examples/hover.html and add `mplcursors.cursor(hover=True)` to my code.

However, the annotation only shown Y value when hovering on the points.

![image](https://user-images.githubusercontent.com/2276718/203461113-b9be0b0e-294d-4cbb-9b53-47a47b7a3b22.png)

After some tries, I have to rewrite the code like this to show both X and Y value.

```python
mplcursors.cursor(ax,hover=True).connect("add", lambda sel: sel.annotation.set_text(f"x: {datetime.fromtimestamp(sel.target_[0]).strftime('%Y-%m-%d %H:%M')} y: {sel.target_[1]}"))
```

Is there any clean or recommended method for achieve this.

**Comment by anntzer** [comment]
Please provide a minimal reproducible example (https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Comment by anntzer** [comment]
Closing for lack of reproducible example, but feel free to ping for reopening if you can provide one.
