### ISSUE TITLE
Error with imshow and colorbar

### ISSUE THREAD

**Issue by davidgilbertson** [anntzer/mplcursors#59]
Howdy.

With a heatmap + colorbar, like:
```py
im = ax.imshow(data)
fig.colorbar(im, ax=ax)
```

Which looks like:
![image](https://user-images.githubusercontent.com/4443482/221046310-6549e6fb-a95c-4342-b850-2a9a84435cb1.png)

An error is thrown when hovering over the colorbar.

Last few lines of the error:
```txt
  File "/.../mplcursors/_pick_info.py", line 337, in _
    sel = _compute_projection_pick(
  File "/.../mplcursors/_pick_info.py", line 246, in _compute_projection_pick
    vertices[codes == tpath.CLOSEPOLY] = vertices[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

IMO it would be fine to swallow this error and just not show a tooltip (maybe `logging.info()` the error message?), but I'm sure there's a more elegant way to handle it.

**Comment by anntzer** [comment]
Thanks for the report.  Should now be fixed as of master, can you give it a try?

**Comment by anntzer** [comment]
Closing per the above.
