### ISSUE TITLE
mplcursors.cursor() not working due to api change in mpl

### ISSUE THREAD

**Issue by xafra** [anntzer/mplcursors#67]
mplcursors.cursor() is not working due to api change in matplotlib

change in _mplcursors.py line 373 could probably fix the issue:

old:
renderer = axes.get_renderer_cache()
new:
renderer = axes.figure.canvas.get_renderer()

**Comment by anntzer** [comment]
This should have been fixed in mplcursors 0.5.2; what version are you using?

**Comment by xafra** [comment]
Was using version 0.5.1. 
Thought I am using version 0.5.2.
Problem is gone, thanks a lot.
