### ISSUE TITLE
Would you consider making a conda package?

### ISSUE THREAD

**Issue by hmaarrfk** [anntzer/mplcursors#7]
Are you still maintaining this project?

It seems to work with python 3.6.
A conda package would be nice. Conda forge could help. I Can help too if you want.

**Comment by anntzer** [comment]
I am actively maintaining the project.
What's wrong with `pip install mplcursors`?  You can do this even from within a conda environment and it will work just fine.  I am not convinced by the need to duplicate packaging efforts.

**Comment by hmaarrfk** [comment]
`pip` has a few issues with different versions of scientific packages, especially when you want to run a version of python that isn't available on your system. For example, ubuntu 16.04, won't install python 3.6 easily.

For windows, conda was the only way I was able to get python to reliably run.

you can run pip from within conda, but then it may not pull in the dependencies correctly.

For the most part, because you have a pure python package, conda-forge bots will do all the work for you, once you have it setup.


For example, my little library got updated automatically by conda-forge, I just had to press accept.
https://github.com/conda-forge/deprecation-factory-feedstock/pulls?q=is%3Apr+is%3Aclosed

**Comment by anntzer** [comment]
Actually, because I have a pure Python package and I did the work to properly declare my dependencies, pip should grab the dependencies correctly, regardless of the version of Python.
I frequently use conda myself to set up envs on Windows but stick to pip to install everything in the env (or nearly everything -- it is true that conda's python doesn't play nice with pypi's PyQt5).
If there are specific failures with `pip install mplcursors` that you have run into, I am happy to look into them.

**Comment by hmaarrfk** [comment]
I'm not saying you wrote your dependencies badly, but for example, I use conda to manage a few C dependencies across computers. 

PyQt5 is quite important for me to get spyder up and running.

Anyway, I'm happy to do the maintenance work to get the conda-forge package running, just wondering if you wanted to be involved. I understand you don't want to duplicate packaging efforts.
Packaging is quite tedious.

Feel free to close this issue.

Thanks for considering.

**Comment by hmaarrfk** [comment]
(Most of all though, thanks for sharing your code !)

**Comment by anntzer** [comment]
I do appreciate your offer to help, but will turn it down for the reasons above.  Again, if it ever does appear that `pip install mplcursors` doesn't work, feel free to report the issue (and likewise for any other problem with mplcursors) and I will look into it.
