### ISSUE TITLE
Draggable issue

### ISSUE THREAD

**Issue by aliada77** [anntzer/mplcursors#71]
Hi,
I create 2 plots on 2 scales as below:
ax1 = plt.subplot(111) and ax2 = ax1.twinx()
when I use mplcursors.cursor(hover=True)
it shows annotation for both scales without any issue but only annotation on ax2 is draggable. 

I even tried mplcursors.cursor([ax1, ax2], hover=True), which didn't work.

Can you pls advise and help in this regard? Thanks!

**Comment by anntzer** [comment]
This is essentially due to a limitation in Matplotlib (https://github.com/matplotlib/matplotlib/issues/815).  Closing, not because it's not a bug but because this needs to be fixed on Matplotlib's side; mplcursors can't do anything about it.

**Comment by aliada77** [comment]
Thanks!
