### ISSUE TITLE
Duble annotation

### ISSUE THREAD

**Issue by aliada77** [anntzer/mplcursors#72]
Hi,

when I have more than one plot created, switching to the first plot I get double annotations.
How can I fix it?
![1](https://github.com/anntzer/mplcursors/assets/83587237/a9dc414f-4752-4b7d-8aa9-0e16c3a9599b)

Thanks!

**Comment by anntzer** [comment]
You didn't provide a minimal repro so I can only guess, but I'd say this is because you need to pass the figure instance to the cursor() call so that it only gets installed on a single figure.

**Comment by aliada77** [comment]
I was using following code:

mplcursors.cursor(hover=True).connect("add", lambda sel: sel.annotation.set_text(mplcursors_annotation(sel)))

When I added fig (as per below), it fixed my issue. Thanks for help :)

mplcursors.cursor([fig], hover=True).connect("add", lambda sel: sel.annotation.set_text(mplcursors_annotation(sel)))
