### ISSUE TITLE
pytest.warns(None) is no longer supported

### ISSUE THREAD

**Issue by wRAR** [anntzer/mplcursors#73]
Not sure what was this code supposed to mean, but on pytest 8 it no longer works: "TypeError: exceptions must be derived from Warning, not <class 'NoneType'>"

https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests

**Comment by anntzer** [comment]
Thanks for the report!  I have now fixed this as of master.
