### ISSUE TITLE
Can't disable multiple key bindings

### ISSUE THREAD

**Issue by ShaiAvr** [anntzer/mplcursors#74]
I am considering using this library to make my plots more interactive, but there is an annoying bug I found. By default, pressing `e` toggles the cursor, and pressing `v` toggles the visibility of the annotation. I don't like these features, and I wanted to disable them. According to the [docs](https://mplcursors.readthedocs.io/en/stable/mplcursors.html#mplcursors.Cursor.__init__), the `bindings` argument should allow me to disable these features. It says that 

> In order to not assign any binding to an action, set it to `None`.

I tried setting them both to `None`:
```python
import matplotlib.pyplot as plt
import numpy as np
import mplcursors

x = np.random.rand(15)
y = np.random.rand(15)
c = np.random.randint(1, 5, size=15)

norm = plt.Normalize(1, 4)
cmap = plt.cm.RdYlGn

fig, ax = plt.subplots()
sc = ax.scatter(x, y, c=c, s=100, cmap=cmap, norm=norm)

mplcursors.cursor(
    sc,
    hover=mplcursors.HoverMode.Transient,
    highlight=True,
    bindings={
        "toggle_enabled": None,
        "toggle_visible": None,
    },
)

plt.show()
```
but got an error: `ValueError: Duplicate bindings: None is used for toggle_enabled and for toggle_visible`. Looking at the [code](https://github.com/anntzer/mplcursors/blob/main/src/mplcursors/_mplcursors.py#L268) it seems that duplicate values are not allowed regardless of whether the value is `None` or not, which means "disable this binding". Therefore, `None` should be allowed to appear multiple times, and I think this is a bug

**Comment by anntzer** [comment]
Thanks for the clear report; this is now fixed.
