### ISSUE TITLE
simulate on_hover

### ISSUE THREAD

**Issue by gbrault** [anntzer/mplcursors#75]
First, thanks for this library: great help for me.

I have an app where I first display a map with scattered dots and I use the hover function to show some text when the mouse is over.
Works perfect!
And this is great for the user to 'discover' the map.

Now, I have a search box which allows to give me the index of a dot in the map. It's not the direct input of the index, but handle some search capability which find the index for the user.

With this index, I would like to show the label which hovering on the dot would give.

Not sure I am fully clear! But if you have any idea!

**Comment by anntzer** [comment]
I think this is somewhat similar to #28: it would be nice if there was a relatively simple API (better than manually sending MouseEvents) to simulate hovering or clicking at certain points.  Let's continue the discussion over there?
