### ISSUE TITLE
Is it possible to get Hovering to work without picking a line?

### ISSUE THREAD

**Issue by Kushtulk** [anntzer/mplcursors#76]
If I want the line with the tooltip to show I have to put the cursors on one of the data lines (see screenshot). Is it possible to get it to show without being on a line, just based on X-value?

![scooter](https://github.com/anntzer/mplcursors/assets/169980696/e7871f34-fb09-4f0c-a900-595d0a277907)

**Comment by anntzer** [comment]
I don't think it is particularly easy to tweak mplcursors to get that behavior (I don't really think it matches mplcursors' design either, as I explicitly don't assume that line plots have x as independent variable and y as dependent variable).  You're more likely to get there by adapting the code at https://matplotlib.org/stable/gallery/event_handling/cursor_demo.html#snapping-to-data-points (for example).
