### ISSUE TITLE
Would you consider building binary wheels for the most common platforms and uploading them to pypi?

### ISSUE THREAD

**Issue by jmoraleda** [anntzer/mplcursors#84]
Hello @anntzer 

Thank you for this project. I use it in a project of mine and I find it very useful. It would be convenient for my project installer, and for the same reasons, others, if  binary wheels for the most common platforms were available in pypi. Would you consider building them and uploading them to pypi?

I think it would be a straight forward automated process using github actions. For example, this is the [github action for a project I contribute to](https://github.com/wxWidgets/Phoenix/blob/master/.github/workflows/ci-build.yml) that I believe has all the pieces required: Compile binary wheels on Linux, MSW and OSX on every commit to the master branch and upload MSW and OSX binary wheels and the tarball to pypi on every "tagged" commit. The jobs `build-documentation` and `upload-wheels-to-snapshot-builds` are not relevant and should be removed and the steps for  dependencies for Linux would need to be modified if there are any dependencies, or removed. Otherwise it would just be changing the name of the project and the build command.[ Adding github as a trusted provider in pypi ](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ )would also be required. 

Let me know what you think. If you are interested I am available to help, but I wouldn't be able to test a github action script, since that would require committer action for the project in both github and pypi. 

Thank you in advance for considering this.

**Comment by anntzer** [comment]
Sure, released v0.6 with a single cross-platform wheel.  Happy to hear you find the project useful.

**Comment by jmoraleda** [comment]
Thank you. That is awesome!
