### ISSUE TITLE
mplcursors with subfigures

### ISSUE THREAD

**Issue by Aethernauter** [anntzer/mplcursors#85]
I would like to use mplcursors on a matplotlib subfigure.
Here is an example code which does not work because of an AttributeError: 'SubFigure' object has no attribute '_canvas_callbacks'
Is it planned to add support for subfigures?

```
import matplotlib.pyplot as plt
import mplcursors

fig = plt.figure()
subfigures=fig.subfigures(2,1)

subfigures[0].suptitle('Testplot')
for i in range(4):
    ax = subfigures[0].add_subplot(2, 2, i + 1)
    ax.plot([1,2,3],[6,5,4])
    cursor = mplcursors.cursor(ax)

fig.show()
```

**Comment by anntzer** [comment]
Are you using matplotlib 3.9?  I suspect your issue has been fixed by https://github.com/matplotlib/matplotlib/pull/27343.

**Comment by Aethernauter** [comment]
You're right, i was using an outdated matplotlib. With Matplotlib 3.9 everything works fine.
Thanks for the quick reply.
